# 2.1.1. Getting Started

In [76]:
x = Float32.([0:1.:11;])  # note the semicolon, and float32 conversion 

12-element Vector{Float32}:
  0.0
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0
 11.0

In [77]:
length(x)

12

In [78]:
size(x)

(12,)

In [79]:
X = reshape(x, 4, 3)'  # julia is column major, hence the reverse dimensions

3×4 adjoint(::Matrix{Float32}) with eltype Float32:
 0.0  1.0   2.0   3.0
 4.0  5.0   6.0   7.0
 8.0  9.0  10.0  11.0

In [80]:
X = reshape(x, :, 3)'  # this does the same thing as above

3×4 adjoint(::Matrix{Float32}) with eltype Float32:
 0.0  1.0   2.0   3.0
 4.0  5.0   6.0   7.0
 8.0  9.0  10.0  11.0

In [81]:
zeros(3, 4, 2)  # again, julia is column major

3×4×2 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [29]:
ones(3,4,2)

3×4×2 Array{Float64, 3}:
[:, :, 1] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

[:, :, 2] =
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [74]:
randn(3, 4)

3×4 Matrix{Float64}:
 -1.5151      1.04244    -0.0253117   1.64663
  0.0602965  -0.0206998  -0.790744   -0.321515
  0.553358    0.797792    0.115701   -0.0138907

# 2.1.2. Indexing and Slicing

In [34]:
X[end, :], X[2:3, :]  # julia is 1-indexed, and can use 'begin' or 'end' to index first or last index

(Float32[8.0, 9.0, 10.0, 11.0], Float32[4.0 5.0 6.0 7.0; 8.0 9.0 10.0 11.0])

In [35]:
X[2, 3] = 17
X

3×4 adjoint(::Matrix{Float32}) with eltype Float32:
 0.0  1.0   2.0   3.0
 4.0  5.0  17.0   7.0
 8.0  9.0  10.0  11.0

In [83]:
X[1:2, :] .= 12  # . operator is used for broadcasting
X

3×4 adjoint(::Matrix{Float32}) with eltype Float32:
 12.0  12.0  12.0  12.0
 12.0  12.0  12.0  12.0
  8.0   9.0  10.0  11.0

# 2.1.3. Operations

In [42]:
exp.(X)

3×4 Matrix{Float32}:
    1.62755f5     1.62755f5      1.62755f5      1.62755f5
    1.62755f5     1.62755f5      1.62755f5      1.62755f5
 2980.96       8103.08       22026.5        59874.1

In [52]:
x = Float64.([1, 2, 4, 8])
y = Float64.([2, 2, 2, 2])
x .+ y, x .- y, x .* y, x ./ y, x .^ y

([3.0, 4.0, 6.0, 10.0], [-1.0, 0.0, 2.0, 6.0], [2.0, 4.0, 8.0, 16.0], [0.5, 1.0, 2.0, 4.0], [1.0, 4.0, 16.0, 64.0])

In [89]:
X = reshape([0.:1.:11.;], :, 3)'
Y = Float64.([
        2 1 4 3;
        1 2 3 4;
        4 3 2 1;
        ])
hcat(X,Y)  # horizontal concatenation

3×8 Matrix{Float64}:
 0.0  1.0   2.0   3.0  2.0  1.0  4.0  3.0
 4.0  5.0   6.0   7.0  1.0  2.0  3.0  4.0
 8.0  9.0  10.0  11.0  4.0  3.0  2.0  1.0

In [65]:
X .== Y

3×4 BitMatrix:
 0  1  0  1
 0  0  0  0
 0  0  0  0

In [66]:
sum(X)

66.0

# 2.1.4. Broadcasting

In [97]:
a = [0:2;]
b = [0:1;]'

1×2 adjoint(::Vector{Int64}) with eltype Int64:
 0  1

In [98]:
a .+ b

3×2 Matrix{Int64}:
 0  1
 1  2
 2  3

# 2.1.5. Saving Memory

In [99]:
before = objectid(Y)
Y = Y + X
objectid(Y) == before

false

In [100]:
Z = similar(Y)  # Z is declared but not initialized
println("id(Z):", objectid(Z))
Z[:] = X + Y
println("id(Z):", objectid(Z))

id(Z):15526999819114664528
id(Z):15526999819114664528


In [101]:
before = objectid(X)  # X += Y doesn't work
X[:] = X + Y
objectid(X) == before

true

In [102]:
# 2.1.6. Conversion to Other Objects
## is skipped