In [86]:
using Statistics

# 2.3.1. Scalars

In [1]:
x = 3.
y = 2.

x + y, x * y, x / y, x^y

(5.0, 6.0, 1.5, 9.0)

# 2.3.2. Vectors

In [4]:
x = Vector(0:2)

3-element Vector{Int64}:
 0
 1
 2

In [6]:
x[3] # 1-based indexing

2

In [8]:
length(x)

3

In [11]:
size(x) # note that the value is a tuple

(3,)

# 2.3.3. Matrices

In [16]:
A = reshape(Vector(0:5), 2, 3)'

3×2 adjoint(::Matrix{Int64}) with eltype Int64:
 0  1
 2  3
 4  5

In [17]:
A'

2×3 Matrix{Int64}:
 0  2  4
 1  3  5

In [18]:
A = [
    1 2 3;
    2 0 4;
    3 4 5;
]

A .== A'

3×3 BitMatrix:
 1  1  1
 1  1  1
 1  1  1

# 2.3.4. Tensors

In [48]:
A = cat(reshape(Vector(0:23), 4, 3, 2)[:, :, 1]', reshape(Vector(0:23), 4, 3, 2)[:, :, 2]', dims=3)

3×4×2 Array{Int64, 3}:
[:, :, 1] =
 0  1   2   3
 4  5   6   7
 8  9  10  11

[:, :, 2] =
 12  13  14  15
 16  17  18  19
 20  21  22  23

# 2.3.5. Basic Properties of Tensor Arithmetic

In [50]:
A = reshape(Vector{Float32}(0:5), 3, 2)'
B = copy(A)
A, A + B

(Float32[0.0 1.0 2.0; 3.0 4.0 5.0], Float32[0.0 2.0 4.0; 6.0 8.0 10.0])

In [51]:
A .* B

2×3 Matrix{Float32}:
 0.0   1.0   4.0
 9.0  16.0  25.0

In [53]:
# PyTorch or other python libraries does not follow linear algebra notations, hence the following ugliness
a = 2
X = cat(reshape(Vector(0:23), 4, 3, 2)[:, :, 1]', reshape(Vector(0:23), 4, 3, 2)[:, :, 2]', dims=3)
a .+ X, size(a * X)

([2 3 4 5; 6 7 8 9; 10 11 12 13;;; 14 15 16 17; 18 19 20 21; 22 23 24 25], (3, 4, 2))

# 2.3.6. Reduction

In [103]:
x = Vector{Float64}(0:2)
x, sum(x)

([0.0, 1.0, 2.0], 3.0)

In [56]:
size(A), sum(A)

((2, 3), 15.0f0)

In [59]:
size(A), size(sum(A, dims=1))

((2, 3), (1, 3))

In [60]:
size(A), size(sum(A, dims=2))

((2, 3), (2, 1))

In [81]:
only(sum(A, dims=(1, 2))) == sum(A)

true

In [88]:
mean(A), sum(A)/length(A)

(2.5f0, 2.5f0)

In [90]:
mean(A, dims=1), sum(A, dims=1) / size(A)[1]

(Float32[1.5 2.5 3.5], Float32[1.5 2.5 3.5])

In [94]:
sum_A = sum(A, dims=2)  # automatically keeps dimensions
sum_A, size(sum_A)

(Float32[3.0; 12.0;;], (2, 1))

In [96]:
A ./ sum_A

2×3 Matrix{Float32}:
 0.0   0.333333  0.666667
 0.25  0.333333  0.416667

In [97]:
cumsum(A, dims=1)

2×3 Matrix{Float32}:
 0.0  1.0  2.0
 3.0  5.0  7.0

# 2.3.8. Dot Products

In [98]:
y = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [106]:
x, y, dot(x, y)

([0.0, 1.0, 2.0], [1.0, 1.0, 1.0], 3.0)

In [107]:
sum(x .* y)

3.0

# 2.3.9. Matrix-Vector Products

In [108]:
size(A), size(x), A * x

((2, 3), (3,), [5.0, 14.0])

# 2.3.10. Matrix-Matrix Multiplication

In [109]:
B = ones(3, 4)
A * B

2×4 Matrix{Float64}:
  3.0   3.0   3.0   3.0
 12.0  12.0  12.0  12.0

# 2.3.11. Norms

In [113]:
u = [3, -4]
norm(u)

5.0

In [115]:
sum(abs.(u))

7

In [116]:
norm(ones(4,9))

6.0